all:
	gcc main.c \
	src/mlSizeSpecification.c \
	src/mlLoadKernelFromSource.c \
	src/mlReleaseResources.c \
	src/mlOutputFromDevice.c \
	src/mlExecCommandQueue.c \
	src/mlInit.c  \
	src/mlInputToDevice.c \
	src/mlProgramBuilder.c \
	src/mlInitKernel.c \
	src/mlGetDeviceAndPlatform.c \
	-o main.exe -Iinclude -lOpenCL
