all:
	gcc main.c src/mlOutputFromDevice.c src/mlExecCommandQueue.c src/kernel_loader.c src/mlInit.c src/mlSizeSpecification.c src/mlInputToDevice.c src/mlProgramBuilder.c src/mlInitKernel.c src/mlGetDeviceAndPlatform.c -o main.exe -Iinclude -lOpenCL
